# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/finn/funcaround

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/finn/funcaround

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/finn/funcaround/CMakeFiles /home/finn/funcaround/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/finn/funcaround/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cl_cppgame

# Build rule for target.
cl_cppgame: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cl_cppgame
.PHONY : cl_cppgame

# fast build rule for target.
cl_cppgame/fast:
	$(MAKE) -f CMakeFiles/cl_cppgame.dir/build.make CMakeFiles/cl_cppgame.dir/build
.PHONY : cl_cppgame/fast

#=============================================================================
# Target rules for targets named sv_cppgame

# Build rule for target.
sv_cppgame: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sv_cppgame
.PHONY : sv_cppgame

# fast build rule for target.
sv_cppgame/fast:
	$(MAKE) -f CMakeFiles/sv_cppgame.dir/build.make CMakeFiles/sv_cppgame.dir/build
.PHONY : sv_cppgame/fast

Actor.o: Actor.cpp.o

.PHONY : Actor.o

# target to build an object file
Actor.cpp.o:
	$(MAKE) -f CMakeFiles/cl_cppgame.dir/build.make CMakeFiles/cl_cppgame.dir/Actor.cpp.o
	$(MAKE) -f CMakeFiles/sv_cppgame.dir/build.make CMakeFiles/sv_cppgame.dir/Actor.cpp.o
.PHONY : Actor.cpp.o

Actor.i: Actor.cpp.i

.PHONY : Actor.i

# target to preprocess a source file
Actor.cpp.i:
	$(MAKE) -f CMakeFiles/cl_cppgame.dir/build.make CMakeFiles/cl_cppgame.dir/Actor.cpp.i
	$(MAKE) -f CMakeFiles/sv_cppgame.dir/build.make CMakeFiles/sv_cppgame.dir/Actor.cpp.i
.PHONY : Actor.cpp.i

Actor.s: Actor.cpp.s

.PHONY : Actor.s

# target to generate assembly for a file
Actor.cpp.s:
	$(MAKE) -f CMakeFiles/cl_cppgame.dir/build.make CMakeFiles/cl_cppgame.dir/Actor.cpp.s
	$(MAKE) -f CMakeFiles/sv_cppgame.dir/build.make CMakeFiles/sv_cppgame.dir/Actor.cpp.s
.PHONY : Actor.cpp.s

Alien.o: Alien.cpp.o

.PHONY : Alien.o

# target to build an object file
Alien.cpp.o:
	$(MAKE) -f CMakeFiles/cl_cppgame.dir/build.make CMakeFiles/cl_cppgame.dir/Alien.cpp.o
	$(MAKE) -f CMakeFiles/sv_cppgame.dir/build.make CMakeFiles/sv_cppgame.dir/Alien.cpp.o
.PHONY : Alien.cpp.o

Alien.i: Alien.cpp.i

.PHONY : Alien.i

# target to preprocess a source file
Alien.cpp.i:
	$(MAKE) -f CMakeFiles/cl_cppgame.dir/build.make CMakeFiles/cl_cppgame.dir/Alien.cpp.i
	$(MAKE) -f CMakeFiles/sv_cppgame.dir/build.make CMakeFiles/sv_cppgame.dir/Alien.cpp.i
.PHONY : Alien.cpp.i

Alien.s: Alien.cpp.s

.PHONY : Alien.s

# target to generate assembly for a file
Alien.cpp.s:
	$(MAKE) -f CMakeFiles/cl_cppgame.dir/build.make CMakeFiles/cl_cppgame.dir/Alien.cpp.s
	$(MAKE) -f CMakeFiles/sv_cppgame.dir/build.make CMakeFiles/sv_cppgame.dir/Alien.cpp.s
.PHONY : Alien.cpp.s

Human.o: Human.cpp.o

.PHONY : Human.o

# target to build an object file
Human.cpp.o:
	$(MAKE) -f CMakeFiles/cl_cppgame.dir/build.make CMakeFiles/cl_cppgame.dir/Human.cpp.o
	$(MAKE) -f CMakeFiles/sv_cppgame.dir/build.make CMakeFiles/sv_cppgame.dir/Human.cpp.o
.PHONY : Human.cpp.o

Human.i: Human.cpp.i

.PHONY : Human.i

# target to preprocess a source file
Human.cpp.i:
	$(MAKE) -f CMakeFiles/cl_cppgame.dir/build.make CMakeFiles/cl_cppgame.dir/Human.cpp.i
	$(MAKE) -f CMakeFiles/sv_cppgame.dir/build.make CMakeFiles/sv_cppgame.dir/Human.cpp.i
.PHONY : Human.cpp.i

Human.s: Human.cpp.s

.PHONY : Human.s

# target to generate assembly for a file
Human.cpp.s:
	$(MAKE) -f CMakeFiles/cl_cppgame.dir/build.make CMakeFiles/cl_cppgame.dir/Human.cpp.s
	$(MAKE) -f CMakeFiles/sv_cppgame.dir/build.make CMakeFiles/sv_cppgame.dir/Human.cpp.s
.PHONY : Human.cpp.s

Weapon.o: Weapon.cpp.o

.PHONY : Weapon.o

# target to build an object file
Weapon.cpp.o:
	$(MAKE) -f CMakeFiles/cl_cppgame.dir/build.make CMakeFiles/cl_cppgame.dir/Weapon.cpp.o
	$(MAKE) -f CMakeFiles/sv_cppgame.dir/build.make CMakeFiles/sv_cppgame.dir/Weapon.cpp.o
.PHONY : Weapon.cpp.o

Weapon.i: Weapon.cpp.i

.PHONY : Weapon.i

# target to preprocess a source file
Weapon.cpp.i:
	$(MAKE) -f CMakeFiles/cl_cppgame.dir/build.make CMakeFiles/cl_cppgame.dir/Weapon.cpp.i
	$(MAKE) -f CMakeFiles/sv_cppgame.dir/build.make CMakeFiles/sv_cppgame.dir/Weapon.cpp.i
.PHONY : Weapon.cpp.i

Weapon.s: Weapon.cpp.s

.PHONY : Weapon.s

# target to generate assembly for a file
Weapon.cpp.s:
	$(MAKE) -f CMakeFiles/cl_cppgame.dir/build.make CMakeFiles/cl_cppgame.dir/Weapon.cpp.s
	$(MAKE) -f CMakeFiles/sv_cppgame.dir/build.make CMakeFiles/sv_cppgame.dir/Weapon.cpp.s
.PHONY : Weapon.cpp.s

WorldObject.o: WorldObject.cpp.o

.PHONY : WorldObject.o

# target to build an object file
WorldObject.cpp.o:
	$(MAKE) -f CMakeFiles/cl_cppgame.dir/build.make CMakeFiles/cl_cppgame.dir/WorldObject.cpp.o
	$(MAKE) -f CMakeFiles/sv_cppgame.dir/build.make CMakeFiles/sv_cppgame.dir/WorldObject.cpp.o
.PHONY : WorldObject.cpp.o

WorldObject.i: WorldObject.cpp.i

.PHONY : WorldObject.i

# target to preprocess a source file
WorldObject.cpp.i:
	$(MAKE) -f CMakeFiles/cl_cppgame.dir/build.make CMakeFiles/cl_cppgame.dir/WorldObject.cpp.i
	$(MAKE) -f CMakeFiles/sv_cppgame.dir/build.make CMakeFiles/sv_cppgame.dir/WorldObject.cpp.i
.PHONY : WorldObject.cpp.i

WorldObject.s: WorldObject.cpp.s

.PHONY : WorldObject.s

# target to generate assembly for a file
WorldObject.cpp.s:
	$(MAKE) -f CMakeFiles/cl_cppgame.dir/build.make CMakeFiles/cl_cppgame.dir/WorldObject.cpp.s
	$(MAKE) -f CMakeFiles/sv_cppgame.dir/build.make CMakeFiles/sv_cppgame.dir/WorldObject.cpp.s
.PHONY : WorldObject.cpp.s

client.o: client.cpp.o

.PHONY : client.o

# target to build an object file
client.cpp.o:
	$(MAKE) -f CMakeFiles/cl_cppgame.dir/build.make CMakeFiles/cl_cppgame.dir/client.cpp.o
.PHONY : client.cpp.o

client.i: client.cpp.i

.PHONY : client.i

# target to preprocess a source file
client.cpp.i:
	$(MAKE) -f CMakeFiles/cl_cppgame.dir/build.make CMakeFiles/cl_cppgame.dir/client.cpp.i
.PHONY : client.cpp.i

client.s: client.cpp.s

.PHONY : client.s

# target to generate assembly for a file
client.cpp.s:
	$(MAKE) -f CMakeFiles/cl_cppgame.dir/build.make CMakeFiles/cl_cppgame.dir/client.cpp.s
.PHONY : client.cpp.s

network.o: network.cpp.o

.PHONY : network.o

# target to build an object file
network.cpp.o:
	$(MAKE) -f CMakeFiles/cl_cppgame.dir/build.make CMakeFiles/cl_cppgame.dir/network.cpp.o
	$(MAKE) -f CMakeFiles/sv_cppgame.dir/build.make CMakeFiles/sv_cppgame.dir/network.cpp.o
.PHONY : network.cpp.o

network.i: network.cpp.i

.PHONY : network.i

# target to preprocess a source file
network.cpp.i:
	$(MAKE) -f CMakeFiles/cl_cppgame.dir/build.make CMakeFiles/cl_cppgame.dir/network.cpp.i
	$(MAKE) -f CMakeFiles/sv_cppgame.dir/build.make CMakeFiles/sv_cppgame.dir/network.cpp.i
.PHONY : network.cpp.i

network.s: network.cpp.s

.PHONY : network.s

# target to generate assembly for a file
network.cpp.s:
	$(MAKE) -f CMakeFiles/cl_cppgame.dir/build.make CMakeFiles/cl_cppgame.dir/network.cpp.s
	$(MAKE) -f CMakeFiles/sv_cppgame.dir/build.make CMakeFiles/sv_cppgame.dir/network.cpp.s
.PHONY : network.cpp.s

server.o: server.cpp.o

.PHONY : server.o

# target to build an object file
server.cpp.o:
	$(MAKE) -f CMakeFiles/sv_cppgame.dir/build.make CMakeFiles/sv_cppgame.dir/server.cpp.o
.PHONY : server.cpp.o

server.i: server.cpp.i

.PHONY : server.i

# target to preprocess a source file
server.cpp.i:
	$(MAKE) -f CMakeFiles/sv_cppgame.dir/build.make CMakeFiles/sv_cppgame.dir/server.cpp.i
.PHONY : server.cpp.i

server.s: server.cpp.s

.PHONY : server.s

# target to generate assembly for a file
server.cpp.s:
	$(MAKE) -f CMakeFiles/sv_cppgame.dir/build.make CMakeFiles/sv_cppgame.dir/server.cpp.s
.PHONY : server.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cl_cppgame"
	@echo "... sv_cppgame"
	@echo "... Actor.o"
	@echo "... Actor.i"
	@echo "... Actor.s"
	@echo "... Alien.o"
	@echo "... Alien.i"
	@echo "... Alien.s"
	@echo "... Human.o"
	@echo "... Human.i"
	@echo "... Human.s"
	@echo "... Weapon.o"
	@echo "... Weapon.i"
	@echo "... Weapon.s"
	@echo "... WorldObject.o"
	@echo "... WorldObject.i"
	@echo "... WorldObject.s"
	@echo "... client.o"
	@echo "... client.i"
	@echo "... client.s"
	@echo "... network.o"
	@echo "... network.i"
	@echo "... network.s"
	@echo "... server.o"
	@echo "... server.i"
	@echo "... server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

